# Production environment override
services:
  php:
    build:
      context: ./api
      target: frankenphp_prod
    environment:
      APP_ENV: prod
      APP_SECRET: ${APP_SECRET}
      SERVER_NAME: http://crypto-curr.digispace.pro, http://php:80
      TRUSTED_HOSTS: ^(localhost|php|crypto-curr\.digispace\.pro|www\.crypto-curr\.digispace\.pro)$
      CORS_ALLOW_ORIGIN: ^https?://(localhost|127\.0\.0\.1|192\.168\.\d+\.\d+|crypto-curr\.digispace\.pro)$
      DATABASE_URL: postgresql://${POSTGRES_USER:-app}:${POSTGRES_PASSWORD:-!ChangeMe!}@database:5432/${POSTGRES_DB:-app}?serverVersion=${POSTGRES_VERSION:-16}&charset=${POSTGRES_CHARSET:-utf8}
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      MERCURE_JWT_SECRET: ${CADDY_MERCURE_JWT_SECRET}
      MERCURE_URL: http://php/.well-known/mercure
      MERCURE_PUBLIC_URL: https://crypto-curr.digispace.pro/.well-known/mercure
    volumes: []

  php-scheduler:
    build:
      context: ./api
      target: frankenphp_prod
    container_name: crypto-app-scheduler-prod
    depends_on:
      - database
    restart: unless-stopped
    command: php bin/console messenger:consume scheduler_default --time-limit=3600 --memory-limit=128M
    environment:
      APP_ENV: prod
      APP_SECRET: ${APP_SECRET}
      TRUSTED_HOSTS: ^(localhost|php|crypto-curr\.digispace\.pro|www\.crypto-curr\.digispace\.pro)$
      TRUSTED_PROXIES: 127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
      CORS_ALLOW_ORIGIN: ^https?://(localhost|127\.0\.0\.1|192\.168\.\d+\.\d+|crypto-curr\.digispace\.pro)$
      DATABASE_URL: postgresql://${POSTGRES_USER:-app}:${POSTGRES_PASSWORD:-!ChangeMe!}@database:5432/${POSTGRES_DB:-app}?serverVersion=${POSTGRES_VERSION:-16}&charset=${POSTGRES_CHARSET:-utf8}
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      MERCURE_JWT_SECRET: ${CADDY_MERCURE_JWT_SECRET}
      MERCURE_URL: http://php/.well-known/mercure
      MERCURE_PUBLIC_URL: https://crypto-curr.digispace.pro/.well-known/mercure
    volumes: []

  pwa:
    build:
      context: ./pwa
      target: prod
    ports:
      - "3000:3000"

  database:
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
