<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260228123347 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // Only create a portfolio_history table
        $this->addSql('CREATE TABLE portfolio_history (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, calculated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, amount_usdt NUMERIC(18, 8) NOT NULL, PRIMARY KEY (id))');
    }

    public function down(Schema $schema): void
    {
        // Only drop the portfolio_history table
        $this->addSql('DROP TABLE portfolio_history');
    }
}
