<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260228122003 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE portfolio (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, asset VARCHAR(10) NOT NULL, amount NUMERIC(18, 8) NOT NULL, trader_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A9ED10621273968F ON portfolio (trader_id)');
        $this->addSql('CREATE TABLE trader (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE portfolio ADD CONSTRAINT FK_A9ED10621273968F FOREIGN KEY (trader_id) REFERENCES trader (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE portfolio DROP CONSTRAINT FK_A9ED10621273968F');
        $this->addSql('DROP TABLE portfolio');
        $this->addSql('DROP TABLE trader');
    }
}
